definitions:
  model.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.LoginResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: |-
    Swagger for backend API service
    Get the Bearer token on the Authentication Service
    JSON Link: <a href=/swagger/doc.json>docs.json</a>
  license: {}
  title: Swagger for go-service
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Endpoint For Login user
      parameters:
      - description: Login Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Login
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
